services:
  samba:
    image: ghcr.io/servercontainers/samba:latest
    restart: always
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    environment:
      MODEL: 'TimeCapsule'
      AVAHI_NAME: maple
      SAMBA_CONF_LOG_LEVEL: 3
      GROUP_family: 1500
      ACCOUNT_yude: "yude:1000:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:75B5E60B60201238F407C266B02C5E2B:[U          ]:LCT-656C60C7:"
      UID_foo: 1000
      GROUPS_foo: family
    volumes:
      - /etc/avahi/services/:/external/avahi
      - /mnt/store1:/mnt/store1
      - /mnt/store3:/mnt/store3
      - /mnt/store4:/mnt/store4
      - /mnt/prod:/mnt/prod
      - ./smb.conf:/etc/samba/smb.conf:ro
