services:
  owntone:
    image: docker.io/owntone/owntone:latest
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/etc/owntone
      - /mnt/store3/music:/srv/media:ro
      - ./cache:/var/cache/owntone
    restart: always
    network_mode: host
