services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./config:/config
      - /mnt/store3/syncthing:/data
    network_mode: host
    restart: always
